# Generated by Django 5.0 on 2024-01-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='battery',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='ram',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='storage',
            new_name='quality',
        ),
    ]
